# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ochko-flow_pagination}
  s.version = "1.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ochirkhuyag.L"]
  s.date = %q{2010-05-19}
  s.description = %q{Replace paginate links with remote 'more' link}
  s.email = %q{ochkoo@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "Manifest",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/flow_pagination.rb",
     "ochko-flow_pagination.gemspec"
  ]
  s.homepage = %q{http://github.com/ochko/flow_pagination}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{FlowPagination link renderer for WillPaginate}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

